version: "3.8"

volumes:
  keydb-data:

services:
  web:
    build: .
    command: ""
    volumes:
      - .:/app/data
    ports:
      - "5000:5000"
    networks:
      -  app-network
    depends_on:
      - keydb

  keydb:
    image: eqalpha/keydb
    command: ""
    volumes:
      - keydb-data:/app/keydb_files
    ports:
      - "6379:6379"
    networks:
      - app-network

  celery:
    build: .
    command: ""
    volumes:
      - .:/app
    environment:
      - REDIS_URL=redis://keydb:6379/0
      - CELERY_BROKER_URL=redis://keydb:6379/0
    depends_on:
      - keydb
    networks:
      - app-network
    

networks:
  app-network:
    driver: bridge

